### ISSUE TITLE
GeoAI

### ISSUE THREAD

**Issue by jakobzhao** [jakobzhao/geog595#7]

**Comment by weixingnie** [comment]
AI is one of the most popular topics in these years. In this week's readings, we first jump in the difference in the definition of  "place" and "space". The idea of place and space expands beyond the limits of the physical boundaries. Even they were considered as similar outside geography, they were one of the endless debates for geographers. The essence of this question framed "how we think about the agency, the origin of somewhere happened, and even social reform". 
Furthermore, we are going to use this knowledge of having a vision at AI. In the reading "Places: A 10 million Image Database for Scene Recognition", Bolei Zhou and his team have attempted using AI to train the computer of imaging and identify scenes. In my own experience, I was honored last winter break to attend this talk with Professor. BoLei Zhou in person at UW campus. Professor. Bolei Zhou patiently described his experience at working AI and introduced to us his main goals --- environment recognition and computer recreation. In their experiments, a computer is powerful enough to identify objects, themes, and cultural identity in one particular environment.  Their accuracy is quite high as well around 95%. However, what I am truly impressed by that is the visualization of units receptive fields. A computer rehandled a photo and changed it according to the input desire. Imagine the impact on the whole art industry, this project has the potential of changing the entire industry. The challenge goes beyond recognition, and it requires a recreation. That is a scary and creepy zone for the use of AI but none can resist its charm. Connecting to another AI-related reading, we see the minimum requirements for creating AI --- big datasets, reproducibility, explicit models, and one solid goal/vision. It requires so many branches to combine together a fundamental influence on AI. The GeoAI and spatial data science seem to have a prominent future by bringing closer to each other. No matter what is lying in the future, we shall never forget the concern on ethics and other issues.

**Comment by erykwaligora** [comment]
I randomly selected the order of the articles to read, but I think this order was very helpful in understanding the full progression of ideas and challenges presented for this week’s theme of GeoAI. The order of the readings went Agnew, Tuan, Janowicz, Zhou. The first two were certainly helpful in understanding the foundational philosophical arguments for “space” and “place” in geography. As both papers note, this examination of has been a critical aspect of geography for many years. Agnew in particular took a deep dive into the juxtaposition of these features, laying out the utter complexity of each, explaining how, for instance, space can be determined by factors like social networks, mobility, identity, etc. Tuan takes these concepts of “space” and “place” even further in applying the “humanistic perspective”. The author overtly ties in how these geographical features are products of the human experience, effectively arguing that “space” and “place” would not exist if not for humanity, and that it is humanity that has given space and place their meaning. He writes, “the modern science of geography derives from man’s sense of place.” Agnew and Tuan’s writings are essential to understand the scope of humanity in the field of geography. This is important as I moved on to the next two readings, which were decisively more immediate to the application of geography tools and challenges today, namely the role that big data sets and AI play within the current landscape. Janowicz provides a thorough explanation of the extent AI has, and will continue, to play in our geographical world. Although the article states that, “ethical consideration should be an essential part of responsible GeoAI research, both on the level of individual researchers as well as the community as a whole” I do not think it went far enough to explain the issues that this technology presents. For instance, it considers drive-by sensors and computer vision as a way to better understand our physical and social environments. But without the humanistic element discussed in the earlier readings, how does this really inform us about our environment if there is no human to place its meaning? More importantly, how does machine learning determine for instance what a “good” neighborhood is versus a “bad” one? Zhou addresses some of the short comings in the Janowicz article by focusing deeply on scene recognition problems and how AI is learning more complex identifiers with millions of images in a dataset. The solution Zhou presents is _more_ visual data for a machine to process and thus provide a more accurate interpretation. This week’s readings made me consider how much we tend to view our spatial world through a lens, Google Maps, Instagram, databases, Uber, etc. We are constantly relying on artificial projections of our “space” and “place”. This is intensified even more if we consider ourselves within the social media, which presents a greater complexity to our understanding our geographical surroundings.
